version: '3.8'

services:
 postgres:
  image: postgres:15
  environment:
    POSTGRE_DB: translation_db
    POSTGRE_USER: postgres
    POSTGRE_PASSWORD: postgres
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - translation_network


  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - translation_network

  translation-api:
    build: ./translation-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABSE_URL=postgresql://postgres:postgres123@postgres:5432/translation_db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - translation_network
    volumes:
      - ./translation-api:/app
      - /app/node_modules

  translation-worker:
    build: ./translation-worker
    environment:
      - NODE_ENV=development
      - DATABSE_URL=postgresql://postgres:postgres123@postgres:5432/translation_db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - translation_network
    volumes:
      - ./translation-api:/app
      - /app/node_modules

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  translation_network:
    driver: bridge
